export const CCMembers = [
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
  {
    name: "Mr. Meow",
    image: "../utils/images/img.png",
    designation: "Member",
    description: "Lorem ipsum dolor sit amet.",
    socialLinks: {
      facebook: "https://www.facebook.com/",
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      github: "https://www.github.com/",
      twitter: "https://www.twitter.com/",
    },
  },
];
